### ISSUE TITLE
LilyPond syntax highlighter doesn't seem to work.

### ISSUE THREAD

**Issue by ksnortum** [uliska/lilyponds-scheme#11]
I'm on Ubuntu 20.04 using a Chrome browser (87) and I don't see any LilyPond syntax highlighting on any of the pages. I only knew that I was supposed to see it because at one point to said, "... as you can see from the syntax lighting."

**Comment by ksnortum** [comment]
I just tried Firefox and no highlighting there either. Tried both Chrome and Firefox on Windows 10; no highlighting.

**Comment by ksnortum** [comment]
I finally see it in the GitHub Preview tab.  It's not working on the website, though.

**Comment by uliska** [comment]
Reason is discussed [here](https://github.com/uliska/lilyponds-scheme/pull/7#issuecomment-735288540). This is not a separate issue
